BookShop/BookManagementPresentation/BookManagementPresentation/Areas/Admin/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BookManagementPresentation.Model;
using BookManagementPresentation.Models;

namespace BookManagementPresentation.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuanLyDonHangController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/QuanLiDonHang
        public ActionResult Index()
        {
            //danh sách các đơn hàng chưa giao+chưa thanh toán
            var listChuaGiao_ChuaThanhToan = db.DonDatHangs.Where(dh => dh.isDelivered == false && dh.isPaid == false).OrderBy(dh => dh.OrderDate);
            return View(listChuaGiao_ChuaThanhToan);
        }


        public ActionResult DaThanhToan_ChuaGiaoHang()
        {
            //danh sách các đơn hàng chưa giao+đã thanh toán
            var listChuaGiao_DaThanhToan = db.DonDatHangs.Where(dh => dh.isDelivered == false && dh.isPaid == true).OrderBy(dh => dh.OrderDate);
            return View(listChuaGiao_DaThanhToan);

        }
        public ActionResult DaThanhToan_DaGiaoHang()
        {
            //danh sách các đơn hàng chưa giao+đã thanh toán
            var listDaGiao_DaThanhToan = db.DonDatHangs.Where(dh => dh.isDelivered == true && dh.isPaid == true).OrderBy(dh => dh.OrderDate);
            return View(listDaGiao_DaThanhToan);
        }
        [HttpGet]
        public ActionResult DuyetDonHang(int? id)
        {
            //kiểm tra id hợp lệ k
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var DonDatHang = db.DonDatHangs.SingleOrDefault(ddh => ddh.DDH_ID == id);
            //kiem tra don dat hang co ton tai k
            if (DonDatHang == null)
            {
                return HttpNotFound();
            }
            //lay chi tiet don hang
            var chiTietDonHangList = db.Carts.Where(ct => ct.DDH_ID == id);
            ViewBag.ListChiTietDonHang = chiTietDonHangList;
            return View(DonDatHang);
        }

        [HttpPost]
        public ActionResult DuyetDonHang(DonDatHang ddh)
        {
            //Truy vấn lấy ra dữ liệu của đơn hàng đó 
            DonDatHang ddhUpdate = db.DonDatHangs.Single(dh => dh.DDH_ID == ddh.DDH_ID);
            ddhUpdate.isPaid = ddh.isPaid;
            ddhUpdate.isDelivered = ddh.isDelivered;
            ddhUpdate.DeliverDate = ddh.DeliverDate;
            db.SaveChanges();

            //Lấy danh sách chi tiết đơn hàng để hiển thị cho người dùng thấy
            var chiTietDonHangList = db.Carts.Where(ct => ct.DDH_ID == ddh.DDH_ID);
            ViewBag.ListChiTietDonHang = chiTietDonHangList;
            //Gửi khách hàng 1 mail để xác nhận việc thanh toán/ giao hàng 
            string paid = "";
            if (bool.Parse(ddhUpdate.isPaid.ToString()))
            {
                paid = "Đã thanh toán";
            }
            else
            {
                paid = "Chưa thanh toán";
            }
            string deliver = "";
            if (bool.Parse(ddhUpdate.isDelivered.ToString()))
            {
                deliver = "Đã giao";
            }
            else
            {
                deliver = "Chưa giao";
            }
            StringBuilder builder = new StringBuilder();
            builder.Append("<table id='table' border='1'><thead><td colspan='5'><table style='width: 100 %; '><tr>");
            builder.Append("<td>Mã đơn hàng: <b style='color: red; '>" + ddhUpdate.DDH_ID + "</b></td>");
            builder.Append("<td>Mã khách hàng: <b style='color: red; '>" + ddhUpdate.MyUser.Id + "</b></td>");
            builder.Append("<td>Tên khách hàng: <b style='color: red; '>" + ddhUpdate.MyUser.Name + "</b></td>");
            builder.Append("<td>Ngày đặt: <b style='color: red; '>" + ddhUpdate.OrderDate.ToString() + "</b></td>");
            builder.Append("<td>Đã thanh toán: <b style='color: red; '>" + paid + "</b></td>");
            builder.Append("<td>Đã giao: <b style='color: red; '>" + deliver + "</b></td>");
            builder.Append("</tr></table></td></tr></thead><thead><tr>");
            builder.Append("<th class='text-center'>Sản Phẩm</th>");
            builder.Append("<th class='text-center'>Số Lượng Đặt</th>");
            builder.Append("<th class='text-center'>Đơn Giá</th>");
            builder.Append("</tr></thead><tbody>");



            int TongSoLuong = 0;
            
            foreach (var item in chiTietDonHangList)
            {

                TongSoLuong += item.Quantity;

                builder.Append("<tr><td class='text-center'>" + item.BookName + "</td>");
                builder.Append("<td class='text-center'>" + item.Quantity + "</td>");
                builder.Append("<td class='text-center'>" + item.Price + "</td></tr>");

            }
            builder.Append("<tr><td align='right' colspan='5'>Tổng số lượng: " + TongSoLuong + " cuốn sách</td></tr>");
            builder.Append("<tr><td align='right' colspan='5'>Tổng tiền: " + double.Parse(ddhUpdate.Total.ToString()).ToString("#,##") + " VNĐ</td></tr>");
            builder.Append("</tbody></table>");
            //string content = System.IO.File.ReadAllText(Server.MapPath(@"~\Areas\Admin\Views\QuanLyDonHang\EmailContent.html"));
            //content = content.Replace("{{MaDonHang}}", ddhUpdate.DDH_ID.ToString());
            //content = content.Replace("{{MaKhachHang}}", ddhUpdate.MyUser.Id);
            //content = content.Replace("{{TenKhachHang}}", ddhUpdate.MyUser.Name);
            //content = content.Replace("{{NgayDat}}", ddhUpdate.OrderDate.ToString());
            //content = content.Replace("{{DaThanhToan}}", ddhUpdate.isPaid.ToString());
            //content = content.Replace("{{DaGiao}}", ddhUpdate.isDelivered.ToString());

            //int TongSoLuong = 0;
            //double TongTien = 0;
            //foreach (var item in chiTietDonHangList)
            //{

            //        TongSoLuong += item.Quantity;

            //    TongTien += (item.Quantity * item.Price);
            //    content = content.Replace("{{TenSach}}", item.BookName);
            //    content = content.Replace("{{HinhAnh}}", "~/"+item.Book.Image);
            //    content = content.Replace("{{SoLuong}}", item.Quantity.ToString());
            //    content = content.Replace("{{DonGia}}", item.Price.ToString("#,##"));

            //}
            //content = content.Replace("{{TongSoLuong}}", TongSoLuong.ToString());
            //content = content.Replace("{{TongTien}}", TongTien.ToString("#,##"));




            MyUser my = db.MyUsers.SingleOrDefault(s=>s.Id == ddh.CusUsername);
            GuiEmail("Xác nhận đơn hàng của nhà sách VAT", my.Email, ConfigurationManager.AppSettings["Email"].ToString(), ConfigurationManager.AppSettings["Password"].ToString(), builder.ToString());
            return View(ddhUpdate);
        }

        public void GuiEmail(string Title, string ToEmail, string FromEmail, string PassWord, string Content)
        {
            // goi email
            MailMessage mail = new MailMessage();
            mail.To.Add(ToEmail); // Địa chỉ nhận
            mail.From = new MailAddress(ToEmail); // Địa chỉ gửi
            mail.Subject = Title;  // tiêu đề gửi
            mail.Body = Content;                 // Nội dung
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com"; // host gửi của Gmail
            smtp.Port = 587;               //port của Gmail
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new System.Net.NetworkCredential
            (FromEmail, PassWord);//Tài khoản password người gửi
            smtp.EnableSsl = true;   //kích hoạt giao tiếp an toàn SSL
            smtp.Send(mail);   //Gửi mail đi
        }
    }
}

BookShop/BookManagementPresentation/BookManagementPresentation/Areas/Admin/Views/QuanLyDonHang/DaThanhToan_ChuaGiaoHang.cshtml
@using BookManagementPresentation.Model
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Thanh Toán Chưa Giao";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    //WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<div id="page-content">
    <!-- Datatables Header -->
    <div class="content-header">
        <ul class="nav-horizontal text-center">
            <li>
                <a href="/Admin/Books"><i class="gi gi-book"></i>Quản lí Sách</a>
            </li>
            <li>
                <a href="/Admin/Categories"><i class="gi gi-shop_window"></i>Quản lí hiệu sách</a>
            </li>
            <li>
                <a href="/Admin/Payments"><i class="gi gi-money"></i>Quản lí thanh toán</a>
            </li>
            <li>
                <a href="/Admin/QuanLyDonHang"><i class="gi gi-shopping_cart"></i>Quản lí đơn hàng</a>
            </li>
            <li>
                <a href="/Admin/Authors"><i class="gi gi-user"></i>Quản lí tác giả</a>
            </li>
            <li>
                <a href="/Admin/Messages"><i class="gi gi-message_ban"></i>Tin nhắn</a>
            </li>
        </ul>
    </div>
    <div class="row text-center">
        @*<div class="col-sm-6 col-lg-3">
            <a href="/Admin/Books/Create" class="widget widget-hover-effect2">
                <div class="widget-extra themed-background-success">
                    <h4 class="widget-content-light"><strong>Thêm mới sách</strong></h4>
                </div>
                <div class="widget-extra-full"><span class="h2 text-success animation-expandOpen"><i class="fa fa-plus"></i></span></div>
            </a>
        </div>*@
        <div class="col-sm-6 col-lg-3">
            <a href="/Home/Index" class="widget widget-hover-effect2">
                <div class="widget-extra themed-background-dark">
                    <h4 class="widget-content-light"><strong>Đi đến cửa hàng</strong></h4>
                </div>
                <div class="widget-extra-full"><span class="h2 themed-color-dark animation-expandOpen">Go</span></div>
            </a>
        </div>
    </div>
    <div class="block full">
        <div class="block-title">
            <h2><strong>Quản lý đơn hàng</strong></h2>
        </div>

        <ul class="nav nav-tabs">
            <li class="li1">
                <a href="@Url.Action("Index","QuanLyDonHang")">CHƯA THANH TOÁN </a>
            </li>
            <li class="li1 active">
                <a href="@Url.Action("DaThanhToan_ChuaGiaoHang","QuanLyDonHang")">ĐÃ THANH TOÁN & CHƯA GIAO </a>
            </li>
            <li class="li1">
                <a href="@Url.Action("DaThanhToan_DaGiaoHang","QuanLyDonHang")">ĐÃ GIAO HÀNG </a>
            </li>

        </ul><br><br />
        <div class="table-responsive">
            @*@grid.GetHtml(
                    tableStyle: "divTable",
                    headerStyle: "gridHead",
                    footerStyle: "gridFooter",
                    rowStyle: "gridRow",
                    alternatingRowStyle: "gridAltRow",
                    columns: grid.Columns(
                        grid.Column("DDH_ID", header: "Mã đơn hàng"),
                        grid.Column("CusUsername", header: "Khách hàng", format: p => p.CusUsername != null ? p.MyUser.Name : ""),
                        grid.Column("OrderDate", header: "Ngày đặt"),
                        grid.Column("isDelivered", header: "Tình trạng giao hàng"),
                        grid.Column("DeliverDate", header: "Ngày giao"),
                        grid.Column("isPaid", header: "Đã thanh toán"),
                        grid.Column("isCanceled", header: "Đã hủy"),
                        grid.Column(format: p=>@Html.ActionLink("Duyệt đơn hàng","DuyetDonHang", new {id=p.DDH_ID}, new {@target="_blank", @class = "btn btn-success", @style = "color:white;" }))
                        )
                )*@
            <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                <thead>
                    <tr>
                        <th class="text-center">Mã Đơn Hàng</th>
                        <th class="text-center">Tên Khách Hàng</th>
                        <th class="text-center">Ngày Mua Hàng</th>
                        <th class="text-center">Tình Trạng Giao</th>
                        <th class="text-center">Ngày Giao Hàng</th>
                        <th class="text-center">Đã thanh toán</th>
                        <th class="text-center">Duyệt</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-center">@item.DDH_ID</td>
                            <td class="text-center">@item.MyUser.Name</td>
                            <td class="text-center">@item.OrderDate</td>
                            @if (item.isDelivered == true)
                            {
                                <td class="text-center">Đã Giao</td>
                            }
                            else
                            {
                                <td class="text-center">Chưa Giao</td>
                            }
                            <td class="text-center">@item.DeliverDate</td>
                            @if (item.isPaid == true)
                            {
                                <td class="text-center">Đã Thanh Toán</td>
                            }
                            else
                            {
                                <td class="text-center">Chưa Thanh Toán</td>
                            }
                            <td class="text-center">
                                <div class="btn-group">
                                    @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = item.DDH_ID }, new { @target = "_blank", @class = "btn btn-success", @style = "color:white;" })
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Datatables Content -->
</div>
@*Css cho controller*@
<style>
    .nav-tabs {
        width: 100%;
    }

    .li1 {
        background: #152F55;
        width: 33.333333333333333%;
        text-align: center;
        font-size: 20px;
        font-weight: 800;
    }




    /*.divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }*/

    /*.gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }*/

    /*.divTable a {
        color: blue;
    }*/

    /*.gridRow {
        background-color: #E2F7F3;
    }

    .gridAltRow {
        background-color: #FCFCFC;
    }*/
</style> 

BookShop/BookManagementPresentation/BookManagementPresentation/Areas/Admin/Views/QuanLyDonHang/DaThanhToan_DaGiaoHang.cshtml
@using BookManagementPresentation.Model
@model IEnumerable<DonDatHang>
@{
    ViewBag.Title = "Thanh Toán Đã Giao";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    //WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}


<div id="page-content">
    <!-- Datatables Header -->
    <div class="content-header">
        <ul class="nav-horizontal text-center">
            <li>
                <a href="/Admin/Books"><i class="gi gi-book"></i>Quản lí Sách</a>
            </li>
            <li>
                <a href="/Admin/Categories"><i class="gi gi-shop_window"></i>Quản lí hiệu sách</a>
            </li>
            <li>
                <a href="/Admin/Payments"><i class="gi gi-money"></i>Quản lí thanh toán</a>
            </li>
            <li>
                <a href="/Admin/QuanLyDonHang"><i class="gi gi-shopping_cart"></i>Quản lí đơn hàng</a>
            </li>
            <li>
                <a href="/Admin/Authors"><i class="gi gi-user"></i>Quản lí tác giả</a>
            </li>
            <li>
                <a href="/Admin/Messages"><i class="gi gi-message_ban"></i>Tin nhắn</a>
            </li>
        </ul>
    </div>
    <div class="row text-center">
        @*<div class="col-sm-6 col-lg-3">
            <a href="/Admin/Books/Create" class="widget widget-hover-effect2">
                <div class="widget-extra themed-background-success">
                    <h4 class="widget-content-light"><strong>Thêm mới sách</strong></h4>
                </div>
                <div class="widget-extra-full"><span class="h2 text-success animation-expandOpen"><i class="fa fa-plus"></i></span></div>
            </a>
        </div>*@
        <div class="col-sm-6 col-lg-3">
            <a href="/Home/Index" class="widget widget-hover-effect2">
                <div class="widget-extra themed-background-dark">
                    <h4 class="widget-content-light"><strong>Đi đến cửa hàng</strong></h4>
                </div>
                <div class="widget-extra-full"><span class="h2 themed-color-dark animation-expandOpen">Go</span></div>
            </a>
        </div>
    </div>
    @*tabs*@

    <div class="block full">
        <div class="block-title">
            <h2><strong>Quản lý đơn hàng</strong></h2>
        </div>

        <ul class="nav nav-tabs">
            <li class="li1">
                <a href="@Url.Action("Index","QuanLyDonHang")">CHƯA THANH TOÁN </a>
            </li>
            <li class="li1">
                <a href="@Url.Action("DaThanhToan_ChuaGiaoHang","QuanLyDonHang")">ĐÃ THANH TOÁN & CHƯA GIAO </a>
            </li>
            <li class="li1 active">
                <a href="@Url.Action("DaThanhToan_DaGiaoHang","QuanLyDonHang")">ĐÃ GIAO HÀNG </a>
            </li>

        </ul><br><br />
                 <div class="table-responsive">
                     @*@grid.GetHtml(
                         tableStyle: "divTable",
                         headerStyle: "gridHead",
                         footerStyle: "gridFooter",
                         rowStyle: "gridRow",
                         alternatingRowStyle: "gridAltRow",
                         columns: grid.Columns(
                             grid.Column("DDH_ID", header: "Mã đơn hàng"),
                             grid.Column("CusUsername", header: "Khách hàng", format: p => p.CusUsername != null ? p.MyUser.Name : ""),
                             grid.Column("OrderDate", header: "Ngày đặt"),
                             grid.Column("isDelivered", header: "Tình trạng giao hàng"),
                             grid.Column("DeliverDate", header: "Ngày giao"),
                             grid.Column("isPaid", header: "Đã thanh toán"),
                             grid.Column("isCanceled", header: "Đã hủy"),
                             grid.Column(format: p=>@Html.ActionLink("Duyệt đơn hàng","DuyetDonHang", new {id=p.DDH_ID}, new {@target="_blank", @class = "btn btn-success", @style = "color:white;" }))
                             )
                     )*@
                     <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
                         <thead>
                             <tr>
                                 <th class="text-center">Mã Đơn Hàng</th>
                                 <th class="text-center">Tên Khách Hàng</th>
                                 <th class="text-center">Ngày Mua Hàng</th>
                                 <th class="text-center">Tình Trạng Giao</th>
                                 <th class="text-center">Ngày Giao Hàng</th>
                                 <th class="text-center">Đã thanh toán</th>
                                 <th class="text-center">Duyệt</th>
                             </tr>
                         </thead>
                         <tbody>
                             @foreach (var item in Model)
                             {
                                 <tr>
                                     <td class="text-center">@item.DDH_ID</td>
                                     <td class="text-center">@item.MyUser.Name</td>
                                     <td class="text-center">@item.OrderDate</td>
                                     @if (item.isDelivered == true)
                                     {
                                         <td class="text-center">Đã Giao</td>
                                     }
                                     else
                                     {
                                         <td class="text-center">Chưa Giao</td>
                                     }
                                     <td class="text-center">@item.DeliverDate</td>
                                     @if (item.isPaid == true)
                                     {
                                         <td class="text-center">Đã Thanh Toán</td>
                                     }
                                     else
                                     {
                                         <td class="text-center">Chưa Thanh Toán</td>
                                     }
                                     <td class="text-center">
                                         <div class="btn-group">
                                             @Html.ActionLink("Duyệt đơn hàng", "DuyetDonHang", new { id = item.DDH_ID }, new { @target = "_blank", @class = "btn btn-success", @style = "color:white;" })
                                         </div>
                                     </td>
                                 </tr>
                             }
                         </tbody>
                     </table>




                 </div>
    </div>

    <!-- END Datatables Content -->


</div>

@*Css cho controller*@
<style>
    .nav-tabs {
        width: 100%;
    }

    .li1 {
        background: #152F55;
        width: 33.333333333333333%;
        text-align: center;
        font-size: 20px;
        font-weight: 800;
    }




    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }

    .divTable a {
        color: blue;
    }

    .gridRow {
        background-color: #E2F7F3;
    }

    .gridAltRow {
        background-color: #FCFCFC;
    }
</style> 

BookShop/BookManagementPresentation/BookManagementPresentation/Areas/Admin/Views/QuanLyDonHang/DuyetDonHang.cshtml
@using BookManagementPresentation.Model
@model DonDatHang
@{
    ViewBag.Title = "Duyệt Đơn";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="page-content">
    <!-- Datatables Header -->
    <div class="content-header">
        <ul class="nav-horizontal text-center">
            <li>
                <a href="/Admin/Books"><i class="gi gi-book"></i>Quản lí Sách</a>
            </li>
            <li>
                <a href="/Admin/Categories"><i class="gi gi-shop_window"></i>Quản lí hiệu sách</a>
            </li>
            <li>
                <a href="/Admin/Payments"><i class="gi gi-money"></i>Quản lí thanh toán</a>
            </li>
            <li>
                <a href="/Admin/QuanLyDonHang"><i class="gi gi-shopping_cart"></i>Quản lí đơn hàng</a>
            </li>
            <li>
                <a href="/Admin/Authors"><i class="gi gi-user"></i>Quản lí tác giả</a>
            </li>
            <li>
                <a href="/Admin/Messages"><i class="gi gi-message_ban"></i>Tin nhắn</a>
            </li>
        </ul>
    </div>
    <div class="row text-center">
        @*<div class="col-sm-6 col-lg-3">
                <a href="/Admin/Books/Create" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background-success">
                        <h4 class="widget-content-light"><strong>Thêm mới sách</strong></h4>
                    </div>
                    <div class="widget-extra-full"><span class="h2 text-success animation-expandOpen"><i class="fa fa-plus"></i></span></div>
                </a>
            </div>*@
        <div class="col-sm-6 col-lg-3">
            <a href="/Home/Index" class="widget widget-hover-effect2">
                <div class="widget-extra themed-background-dark">
                    <h4 class="widget-content-light"><strong>Đi đến cửa hàng</strong></h4>
                </div>
                <div class="widget-extra-full"><span class="h2 themed-color-dark animation-expandOpen">Go</span></div>
            </a>
        </div>
    </div>
    <div class="block full">
        <div class="block-title">
            <h2><strong>Chi tiết đơn đặt hàng của mã đơn hàng: <b style="color:red;"> @Model.DDH_ID  </b></strong></h2>
        </div>
        @using (Html.BeginForm("DuyetDonHang", "QuanLyDonHang", FormMethod.Post, new { @id = "form-validation" }))
        {
            <div class="table-responsive">
                <table id="table" class="table table-vcenter table-condensed table-bordered">
                    @*Phần thông tin đơn hàng*@
                    <thead>
                        <tr>
                            <td colspan="5">
                                <table style="width:100%;">
                                    <tr>

                                        <td>Mã khách hàng: <b style="color:red;"> @Model.MyUser.Id @Html.Hidden("DDH_ID", @Model.DDH_ID)</b></td>
                                        <td>Tên khách hàng: <b style="color:red;"> @Model.MyUser.Name</b></td>
                                        <td>Ngày đặt: @Model.OrderDate.Value.ToString("dd/MM/yyyy")</td>
                                        @if (Model.DeliverDate == null)
                                        {
                                            <td>
                                                Ngày giao: @*@Html.EditorFor(model => model.DeliverDate)*@
                                                <input class="text-box single-line" data-val="true" data-val-date="The field DeliverDate must be a date." id="DeliverDate" name="DeliverDate" type="date" />
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                Ngày giao: @*@Html.EditorFor(model => model.DeliverDate)*@
                                                <input class="text-box single-line" data-val="true" data-val-date="The field DeliverDate must be a date." id="DeliverDate" name="DeliverDate" type="date" value="@Model.DeliverDate.Value.ToString("yyyy-MM-dd")" readonly />
                                                <input type="hidden" id="check-date" value="@Model.isDelivered" />
                                            </td>
                                        }
                                        <td>Đã thanh toán: @Html.EditorFor(model => model.isPaid)</td>
                                        <td>Đã giao: @Html.EditorFor(model => model.isDelivered)</td>
                                    </tr>
                                </table>

                            </td>
                        </tr>
                    </thead>
                    <thead>
                        <tr>
                            <th class="text-center">Số thứ tự</th>
                            <th class="text-center">Sản Phẩm</th>
                            <th class="text-center">Hình Ảnh</th>
                            <th class="text-center">Số Lượng Đặt</th>
                            <th class="text-center">Đơn Giá</th>

                        </tr>
                    </thead>
                    <tbody>
                        @{ int count = 1;

                            IEnumerable<Cart> lstChiTietDH = (IEnumerable<Cart>)ViewBag.ListChiTietDonHang;
                        }
                        @foreach (var item in lstChiTietDH)
                        {
                            <tr>
                                <td class="text-center">@count</td>
                                <td class="text-center">@item.BookName</td>
                                <td class="text-center"><img src="@Url.Content("~/" + item.Book.Image)" width="100" height="150" alt="avatar" class="img-rounded" /></td>
                                <td class="text-center">@item.Quantity</td>
                                <td class="text-center">@item.Price</td>

                            </tr>
                            count++;
                        }

                        <tr>
                            <td align="right" colspan="5">Tổng số lượng: @Model.Carts.Sum(n => n.Quantity) cuốn sách</td>
                        </tr>
                        <tr>
                            <td align="right" colspan="5">Tổng tiền: @double.Parse(Model.Total.ToString()).ToString("#,##") nghìn đồng</td>
                        </tr>
                    </tbody>
                </table><br>
                <input type="hidden" name="CusUsername" value="@Model.MyUser.Id" />
                <button type="submit" class="btn btn-sm btn-primary validDate"><i class="fa fa-angle-right"></i> Lưu đơn hàng</button>
                <button type="submit" class="btn btn-sm btn-warning validDate" id="btnInDonHang"><i class="fa fa-angle-right"></i> In đơn hàng</button>
            </div>
        }
    </div>
    <!-- END Datatables Content -->


</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>

    $("#btnInDonHang").click(function () {
        var content = "<table>" + $("#table").html() + "</table>";
        InDonHang(content);
    });

    //Phương thức in
    function InDonHang(content) {
        var printWindow = window.open('', '', 'height=400,width=800');
        printWindow.document.write('<html><head><title>Thông tin đơn hàng</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(content);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }

</script>
<script>
    $(".validDate").click(function () {
        if (document.getElementById('check-date') === null) {
            var deliverDate = $("#DeliverDate").val();
            var check = $("#isDelivered").val();
            if (check === "false") {
                if (!isNaN(Date.parse(deliverDate.toString()))) {
                    if (Date.parse(deliverDate.toString()) < Date.now()) {
                        alert("Ngày giao hàng phải bắt đầu từ ngày mai!");
                        return false;
                    }
                } 
            } else if (check === "true") {
                if (isNaN(Date.parse(deliverDate.toString()))) {
                    alert("Xin hãy chọn ngày giao hàng!");
                    return false;
                } else {
                    if (Date.parse(deliverDate.toString()) < Date.now()) {
                        alert("Ngày giao hàng phải bắt đầu từ ngày mai!");
                        return false;
                    }
                }
            }
            
        }
    });
</script>